// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX2LFXTyeWyiPbG0OITov5A7rS7u6bDd8',
    appId: '1:444597008216:web:486bc0e0ce944375e0d72d',
    messagingSenderId: '444597008216',
    projectId: 'guyanaevisa',
    authDomain: 'guyanaevisa.firebaseapp.com',
    storageBucket: 'guyanaevisa.appspot.com',
    measurementId: 'G-8R513NVMTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2o0d5F8BHnvJhSGWXt5jayCUV7jfvHY',
    appId: '1:444597008216:android:074ab2d8c6ce240ae0d72d',
    messagingSenderId: '444597008216',
    projectId: 'guyanaevisa',
    storageBucket: 'guyanaevisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVz7gUdhyhZeLWK8QPTJ-jrzn_uaPtl8',
    appId: '1:444597008216:ios:482c0e2f455e7664e0d72d',
    messagingSenderId: '444597008216',
    projectId: 'guyanaevisa',
    storageBucket: 'guyanaevisa.appspot.com',
    iosClientId: '444597008216-lfmb1qgfaom9iltiu0sf7b3elmod46bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.evisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVz7gUdhyhZeLWK8QPTJ-jrzn_uaPtl8',
    appId: '1:444597008216:ios:aa645f9da528ce64e0d72d',
    messagingSenderId: '444597008216',
    projectId: 'guyanaevisa',
    storageBucket: 'guyanaevisa.appspot.com',
    iosClientId: '444597008216-k2haqd33p6llc52doi5hgog2njmppjtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.evisa.RunnerTests',
  );
}
